### ISSUE TITLE
add default "comments" column to Trial submission template

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#732] opened 2017-07-05 14:12 UTC
When downloading the trial submission template, please add a "comments" column to the submission template. The content of this "comments" field should be free text and must be stored in PSU.comments.

To the submission step 4, please add the following text

head:  Comments  ( similar to Trait scores ordering)
In the comments columns, you can add any additional comments that you recorded that were not a trait per se but were important enough to make it into your notes. 
When submitting raw data, you can for example add information about a particular observation, that is not a trait, but useful for the interpretation of a trait or of general interest ( for example, when scoring plant height of a plot, you noticed a flea beetle invasion of that particular plot. Or you noticed that the plot flowered at a weird time, when scoring for flowering time was not actually happening and you were not submitting any traits on flowering time).
It is also helpful for processed data, to document that for example some outliers were removed from that particular entry.

**Comment by kammerer** [comment] 2017-10-11 18:54
Duplicate of #608

**Closed by kammerer** 2017-10-11 18:54 UTC
Labels: enhancement
